# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: polizeiausbildung.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false
    client:
        service-url:
            defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
        hikari:
            maximumPoolSize: 8
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_ADDRESS}
        password: ${MAIL_PASSWORD}
        protocol: smtp
        properties.mail.smtp:
           auth: true
           starttls.enable: true
           ssl.trust: smtp.gmail.com
    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}

        # see https://apps.twitter.com/app/
        twitter:
            client-id: xxx
            client-secret: xxx

        # jhipster-needle-add-social-configuration
