version: '2'
services:
    polizeiausbildung-app:
        image: polizeiausbildung
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://polizeiausbildung-postgresql:5432/polizeiausbildung
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=polizeiausbildung-elasticsearch:9300
        ports:
            - 8080:8080
    polizeiausbildung-postgresql:
        extends:
            file: postgresql.yml
            service: polizeiausbildung-postgresql
    polizeiausbildung-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: polizeiausbildung-elasticsearch
